### ISSUE TITLE
Keanggotaan

### ISSUE THREAD

**Issue by mtaufiqnzz** [RPL5/Elearning5#1]
Tolong kirimkan Nama Akun dan NIM dari masing2 anggota di proyek ini.
terima kasih

**Comment by bayuirfan52** [comment]
Dikirim kemana ya pak? Apa perlu dituliskan ke README.md nya saja?

**Comment by mtaufiqnzz** [comment]
Ditulis di bagian issue aja, di reply aja di sini

**Comment by bayuirfan52** [comment]
16650006 nuranita
16650015 nurchulis
16650018 denisdarwa
16650025 bayuirfan52
16650029 ozianf101
16650047 yakinprabowo
